sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-014
env:
  global:
    -
      # LTD_AWS_ID
      secure: LIWCIKawRpkWwGLX8tqwdBpW5YREs1EO4mI0i5lemjnprFe1yBs75w58voKTn7jRvR7kv9M5OgLl26jbVeIUCMQM7J7jeLJrVassr5FYcBtyF2RZGeGiGZ9QicX6BLGeUnfGUfuc9aTfUb7SRRxFDRjbDip1kwqwiDk4rw9ugisdl8FuceI0k6cW44ksLZFNkfyEJIiC2CtXJZvgDI7IK1hZ4MLfntrbbbo8djhDZUQ0cuHa8PhmXGHvwYv38wkdhEw5w1Eq9RVcuCkzOr0upJ3C54mRZvaIPzUbSI7ckR1N0zKw6TI3q1GrULzRBBwAZWB8PQ13DCPTpF1rkoGjbdIId+TyPnA+/OLmTGYs+raqsIclaJrQMIYqmfoa5FRBpkO3yrdtLl4EvdpZU2BEUJED80f8AHPQDhp4y88Guy6b3fL31N+JW95L9qvtLSMX+BhNIrt8fL53unW9KkPhAEpc3ZZR+6S/WzQlm+IkD9SKyFRLrf/w3zoF6SKWs8MzF57iq3+soEKHSSRA3B6NEyd7jtJg4AlEmXSy7oTprK+mKosrqaIpzCnEzFnIlvk7NF+aa523DqfH0iDlaPEW6l/j1CE/ix1KJSi/i7amBjSSTZSVcWwwbsRk1+Ki77WH0uXfMLGmg9NCsDxNmstIOfEboUmzuCXuQa2ymv8xEQE=
    -
      # LTD_AWS_SECRET
      secure: hHlr6KySn34Y8djAa8OQcVVyC/mGlGRByvvXujbiZFz8oCY9t0fHEXcOnUrRiTnWjZ+tNENkiM3y/Dsf27tY7st96IsijIIUORmLF7uCmOY8Jm9hAQCBdPAkf5mx1bYf/qHyLl3gFQtKVRs8fqtzUZeR9buFxBfckJ6M8EUDfxJOyctXqUI9tAdB6OJ4T1F/MsBr5a7sfpPc1Pv8/Ldrijr6HLa7+JJs5fuynJNjLmjc1jblWKwuyQk/hGh/JN4WKTIS9O/kKEULh21PvXj5aq/rF3AOw4S3g5BvfdTq0r9KOtbsCxKD7erGRtHEOqpzVQ6fyG+llnj+7v5meEKDjOE3Nc9L/8MmA01lWmCb+Yq6VyxG7hDfZg5pbnKXbTkMa/mUghg0kwrYiJ3tzeJO+kf1wEWOFoaYQAJnPwK8Wyyh4fu4izDdyv6TN5BayeygqlAFAYnQg4QA5tDS4NvjPLszIxYDjtMmAXayN/a5Enzlxm0JbVvv8UlRpKVquAIRtj717zfaxkp+DYtKiQESzF8ybnTq2YmliaxkG+tN016I0338B+12kyBclsfqMx6qW7roWR4eqV8qdIcdlpphftXwnjHAeXhVYe5ghqVMlp8nM7Uknmwvx0aF4whUxRoyle4BWFOQkapijLQGXNiJXJbmbXV93IzLtQYaTj+AJqU=
    -
      # LTD_USERNAME
      secure: AEsVEPU3GhMoN9yBIQ6Ked5qXGrFfnJ05AR1KzsnNy0Ustem5LTsojzoBbY3iEBHqjqkkg49MwTSYAi1lTpxm8tp0+Ar8ChmPEDN0kMHoNIhb2qvL8d4gstJhufBroJZT+4eiTX6QiVD1uqZf9FgR1qm282r0zebs4rImmd5akkiA/eS96w5SUr6PDMemY/vduyeCkc+jJrOFccuxj1s82PBgy6msb+6P/1f0PuEqTh8ychZaFFv4ocu6osSqzSp4Zrs2YQllI6ThI4Q66Tlg+uSr2Ji3kzdk+SWO4dx6hi7JWUix56BTG0C6SW0qN4rTBpUW/3V9tdSeuiHQA/JmVp7UC0gE8GBzu5U7Y4NY12vs7YiJbMZljRo/cwkZ+HYe378eAUtrsBGQZamfxZ6ovYmL462WeMNRooRNbRNm/G5k/EMwBR3zHDO9qOqnhi735TELd/ywy7VeOkN+M0lBV+4mUrtA5KIpk94EQaNl4ypUBAULkapsU1iU7pAYFsKtcXjR36n3ncayBjqsu8DS4ricHTu19vPzP6ETou8MHegUT0/k7WpXrA0QVHfUbDoJzmKKj2s31qN6D7XJS1qDVAXM4bMR888+/Jq2vXFbaOvQLt6TUT7/QuUKRqQ4A1wcrpDYWdMyBvPzgG25cbBSNmfdj9kMHmJTN14XGqubsU=
    -
      # LTD_PASSWORD
      secure: EhXyVronqMAfUyxReDeIYpMD6+8P9yFyIsvSXTRDp9I3yvgAASH259e7jwDXGVxixB2vez6orB8nC6E7eoAcW1Dt1Wjo5NuYLeL6ad8P1spLi2LUo6PiBUyY7jn8h/RSIGorWNtjMn0syXbV6G4xsk4Z9ir5VOWr2x4PpB/vZM3aWXAxWmG7YmEZI5pJNwPt25o1YdzuQwjiP0MY//UGEBpn00uWU0t7k45fOXQkBPKLnhuPP86Oh0e50bS22545OZHnL5egpmYZgJocl+K2qhjXgVRLk9fGErMS/IkCv9S81rqp/tqb9zzmMmYtobqbZKQwnDzAjrovXOQ3I2NVXn3gqvN6LOwtVg01wjETm3W1EHNwSO76FTjqNDlm51kfaBOzQVj/OPrYZufMUPWnZK8vhEoRpwRouJPWatKNS9xs7wT5bi9Ed9C3mtT+qthjh0EebODVkb3DPB98VZeAs837ztnixCf9MDJueYDCRIecJqgsxSjINzPFBm/v7fKKEnHR7rtePV6qTAu6KJ57hn8IOBB6jXLE5feJw8y6ZBE++mwBukrKGZgSV9pQh4HkPyK8uKjwmCzedgZUWkL3K3TbQn/qIlFMmANtsHzrOeA0BiH42DcexVndMyBWzuxn6F3fdd96RRhebvx3JpA+m3DSXYEakWojYqNKqU5pXbI=
